### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by nullbio** [LiveBacteria/QNNF-Theory-Integration#1]
Hi. Are you interested in or looking for a collaborator? Have you made much progress with your design?

I've been researching and assembling a blueprint for a novel AI system approach that I believe is more likely to be the correct path forward for an AGI/ASI system for a few months now, and managed to locate your repo when I was searching for similar concepts and designs to what I had envisioned, to see if others were working on the same concepts. There is very little work out there from trying this angle, from what I have seen. Yours was the closest match out of at least 30 repos that I had located. None of the others were close. 

Looking at the description of your system, it sounds like our approach has a lot in common. In saying this, I am yet to develop the code for it and was going to try and find someone to collaborate with first, as this is a big undertaking - and there are always still a lot of finer details to determine. 

Since we seem to be aligned in theory, perhaps we can work together on this? I'm curious if you still see the potential in this approach as well given you've already done some experimentation in-code. How is your outlook on it now? Are you still confident in this direction? 

At the very least it would likely be beneficial for both of us to have a chat on Discord (or some other live-chat) and brainstorm about the theory, architecture and concepts behind all of this. Perhaps we can spark new ideas or insights.

**Comment by LiveBacteria** [comment]
Hey, @nullbio 

I have taken a very interesting tangent on this concept. Do you have a DM of preference? I can send you my current thoughts and the methods I am currently investigating.

You can find me on discord at LiveBacteria#6119

**Comment by nullbio** [comment]
I sent you a friend request :)
